#############################################################
# Bronwyn Woods                                             #
# 2013                                                      #
#                                                           #
# Functions to handle the gui interface to this analysis.   #
#############################################################

##################################################################
# Managing data structures to hold information about experiments #
##################################################################

#-
#' INTERNAL
#' Creates an empty database controller
#' 
#' @details A database controller holds information about the directories
#' where the databases, data, classifiers, and helper files are stored. \cr
#' 
#' @return A list
#' \item{db.directory}{the directory holding SQLite databases}
#' \item{data.directory}{the directory holding data associated with each database. 
#'  each of these should have a \$data element}
#' \item{helper.directory}{the directory in which to place helper files generated by the GUI}
#' \item{classifier.direcoty}{the directory that contains the classifiers used in segmentation}
#' \item{expdf}{a data.frame in which to put information about each experiment, currently empty}
#-
CreateDbController <- function(){
	db.directory <- ""
	data.directory <- ""
	helper.directory <- ""
	classifier.directory <- ""
	expdf <- data.frame(matrix(NA, 0, 5))
	names(expdf) <- c("name", "data file", "database", "classifier", "labeled")
	return(list("db.directory"=db.directory, "data.directory"=data.directory, "helper.directory"=helper.directory,
	"classifier.directory"=classifier.directory, "expdf"=expdf))
}

#-
#' INTERNAL
#' Create an object to store information about the currently selected experiment.
#' 
#' @details Creates a list that stores information about the currently selected experiment.
#' 
#' @return A list with fields to store information about the experiment (initially empty)
#' \item{name}{the experiment name}
#' \item{data}{if loaded, the data object for this object}
#' \item{db}{the database connection for this experiment}
#' \item{nmasks}{the number of candidate masks in the database for this experiment}
#' \item{features}{the tags of the features that exist in this database}
#' \item{sources}{the tage for the mask sources present in this database}
#' \item{selmat}{a matrix where the first column is the ID of the mask and the second column gives the annotation for the mask}
#' \item{sms}{the list of sparse masks for the experiment retreived from the database with GetMasks()}
#' \item{mimg1}{the matrix giving the mean image for channel 1}
#' \item{mimg2}{the matrix giving the mean image for channel 2}
#' \item{nx}{the number of columns in the images for this experiment}
#' \item{ny}{the number of rows in the images}
#-
CreateCurExp <- function(){
	# String giving the name of the selected experiment
	name <- "(na)"
	# The data (if loaded) for the experiment
	data <- NA
	# The connection to this experiment's database
	db <- NA
	# Total number of candidate masks in the database
	nmasks <- 0
	# Vector of names of features in the database
	features <- c()
	# vector of names of the mask sources in the database
	sources <- c()
	# A matrix with the first column being mask id and the second column being the selected status of masks
	selmat <- c()
	# The list of sparse masks as returned by GetMasks()
	sms <- NA
	mimg1 <- NA
	mimg2 <- NA
	nx <- NA
	ny <- NA
	
	return(list("name"=name, "data"=data, "db"=db, "nmasks"=nmasks, "features"=features, "sources"=sources, "selmat"=selmat, "sms"=sms))
}

#-
#' Opens the GUI viewer to manipulate the segmentation process.
#' 
#' @param dbController if specified, the viewer opens with the given dbController (looking
#' in the directories stored in that object)
#' 
#' @return NULL
#-
# TODO: rethink the way data is imported - be more flexible about what the file is called, and look
#       for the $data element
ViewCI <- function(dbController=NULL){
	options(guiToolkit="RGtk2")
			
	# Create an empty dbController if the program wasn't opened with a saved one
	if(is.null(dbController)){
		dbController <- CreateDbController()
	}
	
	curExp=CreateCurExp()
	
	UpdateController <- function(){
		# Update the controller (so far this is used when the directories are changed)
		if(dbController$db.directory != ""){
			dbnames <- unlist(sapply(list.files(dbController$db.directory, pattern="[:alnum:]*.sqlite"), strsplit, split=".sqlite"))
		}else{
			dbname  <- c()
		}
		if(dbController$data.directory != ""){
			datanames <- unlist(sapply(list.files(dbController$data.directory, pattern="[:alnum:]*.Rdata"), strsplit, split=".Rdata"))
		}else{
			datanames <- c()
		}
		names <- sort(unique(c(dbnames, datanames)))
		dbController$expdf <<- data.frame(cbind(names, matrix(NA, length(names), 4)), stringsAsFactors=FALSE)
		names(dbController$expdf) <<- c("name", "data file", "database", "classifier", "labeled")
		for(i in 1:length(names)){
			dbController$expdf[i,2] <<- dbController$expdf[i,1] %in% datanames
			dbController$expdf[i,3] <<- dbController$expdf[i,1] %in% dbnames
		}
		exptable[] <- dbController$expdf
	}
	
	UpdateDbDirectory <- function(h,...){
		# Set the database directory
		dbController$db.directory <<- h$file
		UpdateController()
		svalue(dir.ref.dbdirectory) <- dbController$db.directory
	}
	
	FindDbDirectory <- function(h,...){
		# Respond to the user clicking the "find" button for the database directory
		gfile(type="selectdir", handler = UpdateDbDirectory)
	}
	
	UpdateClassifierDirectory <- function(h,...){
		# Set the database directory
		dbController$classifier.directory <<- h$file
		UpdateController()
		svalue(dir.ref.classifierdirectory) <- dbController$classifier.directory
	}
	
	FindClassifierDirectory <- function(h,...){
		# Respond to the user clicking the "find" button for the classifier directory
		gfile(type="selectdir", handler = UpdateClassifierDirectory)
	}
	
	UpdateHelperDirectory <- function(h,...){
		# Set the database directory
		dbController$helper.directory <<- h$file
		UpdateController()
		svalue(dir.ref.helperdirectory) <- dbController$helper.directory
	}
	
	FindHelperDirectory <- function(h,...){
		# Respond to the user clicking the "find" button for the helper directory
		gfile(type="selectdir", handler = UpdateHelperDirectory)
	}
	
	UpdateDataDirectory <- function(h,...){
		# Set the data file directory
		dbController$data.directory <<- h$file
		UpdateController()
		svalue(dir.ref.datadirectory) <- dbController$data.directory
	}
	
	FindDataDirectory <- function(h,...){
		# Respond to the user clicking the "find" button for the data directory
		gfile(type="selectdir", handler = UpdateDataDirectory)
	}
	
	SaveSession <- function(h, ...){
		# Save the dbController object
		SaveSessionHelper <- function(h,...){
			save(dbController, file=h$file)
		}
		gfile(type="save", handler=SaveSessionHelper)
	}
	
	LoadSession <- function(h,...){
		# Load a dbController object
		LoadSessionHelper <- function(h,...){
			load(file=h$file)
			h$file <- dbController$db.directory
			UpdateDbDirectory(h)
			h$file <- dbController$data.directory
			UpdateDataDirectory(h)
			h$file <- dbController$classifier.directory
			UpdateClassifierDirectory(h)
			h$file <- dbController$helper.directory
			UpdateHelperDirectory(h)
			exptable[] <- dbController$expdf
		}
		gfile(type="open", handler=LoadSessionHelper)		
	}
	
	AddLabeledMasks <- function(){
		visible(imgwindow3) <- TRUE			
		myimage(curExp$mimg1, useRaster=T)
		visible(imgwindow4) <- TRUE						
		myimage(curExp$mimg2, useRaster=T)
		maskmat = matrix(0, curExp$ny, curExp$nx)		
		for(i in 1:nrow(curExp$selmat)){
			if(!is.na(curExp$selmat[i,2]) && abs(curExp$selmat[i,2])==1){
				maskmat <- maskmat+smtomat(curExp$sms[[i]], curExp$ny, curExp$nx, background=0)
			}
		}
		if(max(maskmat)>0){		
			print("about to add masks")	
			visible(imgwindow3) <- TRUE
			addmaskset(maskmat, rgb=c(0,1,0), useRaster=T)
			visible(imgwindow4) <- TRUE
			addmaskset(maskmat, rgb=c(0,1,0), useRaster=T)
		}
	}
			
	# When someone clicks on or selects a region in the image
	ImgHandler <- function(h, ...){
		PlotPage <- function(pnum){
			for(i in 1:5){
				snum = 5*(pnum-1)+(i-1)
				for(j in 1:5){
					if(snum*5+j<=length(ovlpind)){
						id = -1* curExp$sms[[ovlpind[sizeorder[snum*5+j]]]][1]
						label = curExp$selmat[which(curExp$selmat[,1]==id),2]
						if(is.na(label) || label==0){
							rgb=c(0,0,1)
						}else if(label==1){
							rgb=c(0,1,0)
						}else{
							rgb=c(1,0,0)
						}
						visible(ref.mswin[[(i-1)*5+j]]) <- TRUE
						par(mar=c(0.1,0.2,0.1,0.1), mfrow=c(1,2))
						myimage(curExp$mimg1[yrange[1]:yrange[2], xrange[1]:xrange[2]], useRaster=T)
						addmask(smtomat(curExp$sms[[ovlpind[sizeorder[snum*5+j]]]], curExp$ny, curExp$nx)[yrange[1]:yrange[2], xrange[1]:xrange[2]], rgb=rgb, useRaster=T)
						par(mar=c(0.1,0.1,0.1,0.2))
						myimage(curExp$mimg2[yrange[1]:yrange[2], xrange[1]:xrange[2]], useRaster=T)
						addmask(smtomat(curExp$sms[[ovlpind[sizeorder[snum*5+j]]]], curExp$ny, curExp$nx)[yrange[1]:yrange[2], xrange[1]:xrange[2]], rgb=rgb, useRaster=T)
					}else{
						visible(ref.mswin[[(i-1)*5+j]]) <- TRUE
						mat = matrix(1, diff(yrange), diff(xrange))
						mat[,1]=0
						myimage(mat)
					}
				}
			}
			if(25*(pnum) >=length(ovlpind)){
				enabled(mswin.nextbutton) <- FALSE
			}else{
				enabled(mswin.nextbutton) <- TRUE
			}
			if(pnum>1){
				enabled(mswin.prevbutton) <- TRUE
			}else{
				enabled(mswin.prevbutton) <- FALSE
			}
		}			
		
		PagePrev <- function(h, ...){
			curpage <<- curpage-1
			PlotPage(curpage)
			svalue(mswin.pagelabel) <- paste("Showing ", (curpage-1)*25+1,"-", min(curpage*25,length(ovlpind)), " of ", length(ovlpind), sep="")				
		}
		
		PageNext <- function(h, ...){
			curpage <<- curpage+1
			PlotPage(curpage)
			svalue(mswin.pagelabel) <- paste("Showing ", (curpage-1)*25+1,"-", min(curpage*25,length(ovlpind)), " of ", length(ovlpind), sep="")
		}
		
		MarkNegative <- function(h, ...){
			# mark any unmarked masks in the current set as false positives
			for(i in 1:length(ovlpind)){
				selmatrow = which(curExp$selmat[,1]==ovlpind[i])
				curlabel = curExp$selmat[selmatrow,2]
				if(is.na(curlabel) || curlabel==0){
					curExp$selmat[selmatrow,2] <<- 2
					SetMaskLabel(curExp$db, -1*curExp$sms[[ovlpind[i]]][1], 2)
				}
			}
			PlotPage(curpage)
		}

		
		CloseLabelWindow <- function(h, ...){
			AddLabeledMasks()
			dispose(mswin)
		}
	
		SetLabel <- function(index){
			ind = (curpage-1)*25+index
			if(ind<=length(ovlpind)){
				id = -1* curExp$sms[[ovlpind[sizeorder[ind]]]][1]
				label = curExp$selmat[which(curExp$selmat[,1]==id),2]
				if(is.na(label) || label==0){
					# Currently unlabeled
					# Change to cell
					label <- 1
					rgb=c(0,1,0)
				}else if(label==2){
					# Currently marked as false positive
					# Change to unlabeled
					label <- 0
					rgb=c(0,0,1)
				}else{
					# Currently marked as cell
					# change to negative
					label <- 2
					rgb=c(1,0,0)
				}
				# change selmat
				curExp$selmat[which(curExp$selmat[,1]==id),2] <<- label
				# update in database
				SetMaskLabel(curExp$db, id, label)	
				
				visible(ref.mswin[[index]]) <- TRUE
				par(mar=c(0.1,0.2,0.1,0.1), mfrow=c(1,2))
				myimage(curExp$mimg1[yrange[1]:yrange[2], xrange[1]:xrange[2]], useRaster=T)
				addmask(smtomat(curExp$sms[[ovlpind[sizeorder[ind]]]], curExp$ny, curExp$nx)[yrange[1]:yrange[2], xrange[1]:xrange[2]], rgb=rgb, useRaster=T)
				par(mar=c(0.1,0.1,0.1,0.2))
				myimage(curExp$mimg2[yrange[1]:yrange[2], xrange[1]:xrange[2]], useRaster=T)
				addmask(smtomat(curExp$sms[[ovlpind[sizeorder[ind]]]], curExp$ny, curExp$nx)[yrange[1]:yrange[2], xrange[1]:xrange[2]], rgb=rgb, useRaster=T)
			}
		}
		SetLabel1 <- function(h, ...){SetLabel(1)}
		SetLabel2 <- function(h, ...){SetLabel(2)}
		SetLabel3 <- function(h, ...){SetLabel(3)}
		SetLabel4 <- function(h, ...){SetLabel(4)}
		SetLabel5 <- function(h, ...){SetLabel(5)}
		SetLabel6 <- function(h, ...){SetLabel(6)}
		SetLabel7 <- function(h, ...){SetLabel(7)}
		SetLabel8 <- function(h, ...){SetLabel(8)}
		SetLabel9 <- function(h, ...){SetLabel(9)}
		SetLabel10 <- function(h, ...){SetLabel(10)}
		SetLabel11 <- function(h, ...){SetLabel(11)}
		SetLabel12 <- function(h, ...){SetLabel(12)}
		SetLabel13 <- function(h, ...){SetLabel(13)}
		SetLabel14 <- function(h, ...){SetLabel(14)}
		SetLabel15 <- function(h, ...){SetLabel(15)}
		SetLabel16 <- function(h, ...){SetLabel(16)}
		SetLabel17 <- function(h, ...){SetLabel(17)}
		SetLabel18 <- function(h, ...){SetLabel(18)}
		SetLabel19 <- function(h, ...){SetLabel(19)}
		SetLabel20 <- function(h, ...){SetLabel(20)}
		SetLabel21 <- function(h, ...){SetLabel(21)}
		SetLabel22 <- function(h, ...){SetLabel(22)}
		SetLabel23 <- function(h, ...){SetLabel(23)}
		SetLabel24 <- function(h, ...){SetLabel(24)}
		SetLabel25 <- function(h, ...){SetLabel(25)}
		
		xrange <- round(h$x*128)
		yrange <- h$y
		yrange = round((1-yrange)*128)[2:1]

		if(diff(xrange)==0 && diff(yrange)==0){
			#only one point selected
		}else{
			#rectangle selected
			mask = matrix(NA, curExp$ny, curExp$nx)
			mask[yrange[1]:yrange[2], xrange[1]:xrange[2]]=1
		
			# the indices in sms which are contained int he selected region
			# sms and selmat are currently assumed to be in the same order since
			#   both were obtained from the database with order by id
			ovlpind <- which(!compMaskC(mattosm(invertmask(mask)), curExp$sms))
			msizes <- as.vector(sapply(curExp$sms[ovlpind], length))
			sizeorder <- order(msizes, decreasing=T)

			# Create the window to allow users to label the masks in ovlp
			mswin <- gwindow("Label Candidate Masks", visible=FALSE)
			mswin.imggroup <- ggroup(container=mswin, horizontal=FALSE)
			mswin.refgroup <- ggroup(container=mswin.imggroup, expand=FALSE)
			mswin.junk1 <- ggraphics(width=400, height=100, container=mswin.refgroup)			
			mswin.refimg1 <- ggraphics(width=100, height=100, container=mswin.refgroup)
			mswin.refimg2 <- ggraphics(width=100, height=100, container=mswin.refgroup)
			mswin.junk2 <- ggraphics(width=400, height=100, container=mswin.refgroup)			

			mswin.imgrow1 <- ggroup(container=mswin.imggroup)
			mswin.imgrow2 <- ggroup(container=mswin.imggroup)
			mswin.imgrow3 <- ggroup(container=mswin.imggroup)
			mswin.imgrow4 <- ggroup(container=mswin.imggroup)
			mswin.imgrow5 <- ggroup(container=mswin.imggroup)
			
			imgmask1 <- ggraphics(width=200, height= 100, container=mswin.imgrow1)
			addHandlerChanged(imgmask1, SetLabel1)
			imgmask2 <- ggraphics(width=200, height= 100, container=mswin.imgrow1)
			addHandlerChanged(imgmask2, SetLabel2)
			imgmask3 <- ggraphics(width=200, height= 100, container=mswin.imgrow1)
			addHandlerChanged(imgmask3, SetLabel3)
			imgmask4 <- ggraphics(width=200, height= 100, container=mswin.imgrow1)
			addHandlerChanged(imgmask4, SetLabel4)
			imgmask5 <- ggraphics(width=200, height= 100, container=mswin.imgrow1)
			addHandlerChanged(imgmask5, SetLabel5)
			imgmask6 <- ggraphics(width=200, height= 100, container=mswin.imgrow2)
			addHandlerChanged(imgmask6, SetLabel6)
			imgmask7 <- ggraphics(width=200, height= 100, container=mswin.imgrow2)
			addHandlerChanged(imgmask7, SetLabel7)
			imgmask8 <- ggraphics(width=200, height= 100, container=mswin.imgrow2)
			addHandlerChanged(imgmask8, SetLabel8)
			imgmask9 <- ggraphics(width=200, height= 100, container=mswin.imgrow2)
			addHandlerChanged(imgmask9, SetLabel9)
			imgmask10 <- ggraphics(width=200, height= 100, container=mswin.imgrow2)
			addHandlerChanged(imgmask10, SetLabel10)
			imgmask11 <- ggraphics(width=200, height= 100, container=mswin.imgrow3)
			addHandlerChanged(imgmask11, SetLabel11)
			imgmask12 <- ggraphics(width=200, height= 100, container=mswin.imgrow3)
			addHandlerChanged(imgmask12, SetLabel12)
			imgmask13 <- ggraphics(width=200, height= 100, container=mswin.imgrow3)
			addHandlerChanged(imgmask13, SetLabel13)
			imgmask14 <- ggraphics(width=200, height= 100, container=mswin.imgrow3)
			addHandlerChanged(imgmask14, SetLabel14)
			imgmask15 <- ggraphics(width=200, height= 100, container=mswin.imgrow3)
			addHandlerChanged(imgmask15, SetLabel15)
			imgmask16 <- ggraphics(width=200, height= 100, container=mswin.imgrow4)
			addHandlerChanged(imgmask16, SetLabel16)
			imgmask17 <- ggraphics(width=200, height= 100, container=mswin.imgrow4)
			addHandlerChanged(imgmask17, SetLabel17)
			imgmask18 <- ggraphics(width=200, height= 100, container=mswin.imgrow4)
			addHandlerChanged(imgmask18, SetLabel18)
			imgmask19 <- ggraphics(width=200, height= 100, container=mswin.imgrow4)
			addHandlerChanged(imgmask19, SetLabel19)
			imgmask20 <- ggraphics(width=200, height= 100, container=mswin.imgrow4)
			addHandlerChanged(imgmask20, SetLabel20)
			imgmask21 <- ggraphics(width=200, height= 100, container=mswin.imgrow5)
			addHandlerChanged(imgmask21, SetLabel21)
			imgmask22 <- ggraphics(width=200, height= 100, container=mswin.imgrow5)
			addHandlerChanged(imgmask22, SetLabel22)
			imgmask23 <- ggraphics(width=200, height= 100, container=mswin.imgrow5)
			addHandlerChanged(imgmask23, SetLabel23)
			imgmask24 <- ggraphics(width=200, height= 100, container=mswin.imgrow5)
			addHandlerChanged(imgmask24, SetLabel24)
			imgmask25 <- ggraphics(width=200, height= 100, container=mswin.imgrow5)
			addHandlerChanged(imgmask25, SetLabel25)
			ref.mswin <- list(imgmask1, imgmask2, imgmask3, imgmask4, imgmask5, imgmask6, imgmask7, imgmask8, imgmask9,
				imgmask10, imgmask11, imgmask12, imgmask13, imgmask14, imgmask15, imgmask16, imgmask17, imgmask18, imgmask19, imgmask20,
				imgmask21, imgmask22, imgmask23, imgmask24, imgmask25)
			
			
			visible(mswin) <- TRUE
			visible(mswin.refimg1) <- TRUE
			par(mar=rep(0,4))
			myimage(curExp$mimg1[yrange[1]:yrange[2], xrange[1]:xrange[2]], useRaster=T)		
			visible(mswin.refimg2) <- TRUE
			par(mar=rep(0,4))
			myimage(curExp$mimg2[yrange[1]:yrange[2], xrange[1]:xrange[2]], useRaster=T)
			

			# Set the first page to 1
			curpage=1
			# Navigation buttons
			mswin.navgroup <- ggroup(container=mswin.imggroup)
			mswin.prevbutton <- gbutton(text="Previous Page", handler=PagePrev, container=mswin.navgroup)
			enabled(mswin.prevbutton) <- FALSE
			mswin.pagelabel <- glabel(text=paste("Showing 1-", min(25, length(ovlpind)), " of ", length(ovlpind), sep=""), container=mswin.navgroup)
			mswin.nextbutton <- gbutton(text="Next Page", handler=PageNext, container=mswin.navgroup)
			mswin.allnegative <- gbutton(text="Mark unlabeled masks negative", handler=MarkNegative, container=mswin.navgroup)
			mswin.closewindow <- gbutton(text="Close window", handler=CloseLabelWindow, container=mswin.navgroup)
			if(length(ovlpind)<=25){
				enabled(mswin.nextbutton) <- FALSE
			}
			# Plot the first page
			PlotPage(curpage)
		}
	}
	
	# Updates the information in the experiment details section
	UpdateExpDetails <- function(h, ...){
		svalue(det.ref.name) <- curExp$name
		svalue(det.ref.nmasks) <- toString(curExp$nmasks)
		svalue(det.ref.features) <- paste(curExp$features, collapse=", ")
		svalue(det.ref.sources) <- paste(curExp$sources, collapse=", ")		
	}
	
	SelectExperiment <- function(h, ...){
		cat("LOADING...")
		# Experiment name
		curExp$name <<- svalue(exptable) 
		# The connection to this experiment's database
		db <- conMaskDb(paste(dbController$db.directory, "/", curExp$name, ".sqlite", sep="")) 
		curExp$db <<- db
		# Total number of candidate masks in the database
		curExp$nmasks <<- nrow(deq(db, "select id from masks"))
		# List of names of features in the database
		allfeats = deq(db, "select tag from features")[,1]

		cat("1 ")
		
		issource <- function(ftag){
			return(charmatch("source_", ftag, 0))
		}
		sourceind <- sapply(allfeats, issource)

		curExp$features <<- allfeats[which(sourceind==0)]
		# List of names of the mask sources in the database
		curExp$sources <<- allfeats[which(sourceind==1)]
		# The list of sparse masks as returned by GetMasks()
		curExp$sms <<- GetMasks(db)

		cat("2 ")
		
		# A matrix with the first column being mask id and the second column being the selected status of masks
		curExp$selmat <<- deq(db, "select id, label from masks order by id")

		cat("3 ")
		
		dims = deq(db, "select nx, ny from experiments")
		curExp$nx <<- as.integer(dims[1,1])
		curExp$ny <<- dims[1,2]	

		cat("3b ")
		
		# Load the data file by default if the img1 and img2 files aren't in the helper directory
		curExp$helperfiles <<- list.files(dbController$helper.directory, pattern=paste(curExp$name,"[:alnum:]*", sep=""))
		mimg1name  <- grep("mimg1", curExp$helperfiles, value=T)
		mimg2name  <- grep("mimg2", curExp$helperfiles, value=T)
		cat("4 ")
		if(length(mimg1name)>0 && length(mimg2name)>0){
			load(paste(dbController$helper.directory, "/", mimg1name, sep=""))
			load(paste(dbController$helper.directory, "/", mimg2name, sep=""))
			curExp$mimg1 <<- mimg1
			curExp$mimg2 <<- mimg2
		}else{
			load(paste(dbController$data.directory, "/", curExp$name, ".Rdata", sep=""))
			curExp$data <<- get(paste(curExp$name, "data", sep=""))
			mimg1 <- apply(curExp$data[1,,,], c(2,3), mean)
			mimg2 <- apply(curExp$data[2,,,], c(2,3), mean)
			save(mimg1, file=paste(dbController$helper.directory, "/", curExp$name, ".mimg1", sep=""))
			save(mimg2, file=paste(dbController$helper.directory, "/", curExp$name, ".mimg2", sep=""))
			rm(list=paste(curExp$name, "data", sep=""))
		
			curExp$mimg1 <<- mimg1
			curExp$mimg2 <<- mimg2		
		}
		cat("5 ")
		
		visible(imgwindow1) <- TRUE
		par(mar=c(0,0,0,0))
		myimage(curExp$mimg1, useRaster=T)

		visible(imgwindow2) <- TRUE
		par(mar=c(0,0,0,0))
		myimage(curExp$mimg2, useRaster=T)

		visible(imgwindow3) <- TRUE
		par(mar=c(0,0,0,0))
		myimage(curExp$mimg1, useRaster=T)

		visible(imgwindow4) <- TRUE
		par(mar=c(0,0,0,0))
		myimage(curExp$mimg2, useRaster=T)
		
		UpdateExpDetails(NA)
		AddLabeledMasks()
		
		cat("done\n")
	}
	
	
	########## Layout
	
	##The widgets
	win <- gwindow("Calcium Imaging Segmenter", spacing=10)
	maingroup <- ggroup(cont=win, spacing=5)
	navgroup <- ggroup(horizontal=FALSE, cont=maingroup)
	vexpgroup <- ggroup(horizontal=FALSE, cont=maingroup, expand=TRUE, spacing=10)
	
	############################
	##### Navigation group
	
	# Setting and showing the directories chosen for the dbs and data
	directory.frame <- gframe("Directories", container=navgroup, horizontal=F)
	directory.layout  <- glayout(container=directory.frame)
	directory.layout[1,1:3, expand=T] <- "Please specify the appropriate data directories:                           "
	directory.layout[2,1] <- "Database directory: "
	directory.layout[4,1] <- "Data directory: "
	directory.layout[6,1] <- "Classifier directory: "
	directory.layout[8,1] <- "Helper directory (for misc file storage): "
	directory.layout[3,1, expand=T] <- glabel(text=dbController$db.directory)
	directory.layout[5,1, expand=T] <- glabel(text=dbController$data.directory)
	directory.layout[7,1, expand=T] <- glabel(text=dbController$classifier.directory)
	directory.layout[9,1, expand=T] <- glabel(text=dbController$helper.directory)
	directory.layout[3,2] <- gbutton(text="...", handler = FindDbDirectory)
	directory.layout[5,2] <- gbutton(text="...", , handler = FindDataDirectory)
	directory.layout[7,2] <- gbutton(text="...", , handler = FindClassifierDirectory)
	directory.layout[9,2] <- gbutton(text="...", , handler = FindHelperDirectory)
	dir.ref.dbdirectory <- directory.layout[3,1]
	dir.ref.datadirectory <- directory.layout[5,1]
	dir.ref.classifierdirectory <- directory.layout[7,1]
	dir.ref.helperdirectory <- directory.layout[9,1]
	
	# Showing the experiments that have been found
	experiments.frame <- gframe("Experiments", container=navgroup, horizontal=F, expand=TRUE)
	exptable <- gtable(dbController$expdf, container=experiments.frame, drop=FALSE, expand=TRUE, handler=SelectExperiment)
	visible(exptable) <- FALSE
	
	# Save the database controller to be used in another session
	controller.group <- ggroup(container=navgroup)
	save.controller <- gbutton(text="Save Session", container=controller.group, handler=SaveSession)
	load.controller <- gbutton(text="Load Session", container=controller.group, handler=LoadSession)
	
	############################
	##### view experiment group
	details.frame <- gframe("Experiment Details", container=vexpgroup, horizontal=F)
	details.layout <- glayout(container=details.frame)
	details.layout[1,1] <- "Experiment name:"
	details.layout[1,2] <- glabel(text=curExp$name)
	details.layout[2,1] <- "Number of masks:"
	details.layout[2,2] <- glabel(text=toString(curExp$nmasks))
	details.layout[3,1] <- "Sources:"
	details.layout[3,2] <- glabel(text=paste(curExp$sources, collapse=", "))
	details.layout[4,1] <- "Features:"
	details.layout[4,2] <- glabel(text=paste(curExp$features, collapse=", "))
	det.ref.name <- details.layout[1,2]
	det.ref.nmasks <- details.layout[2,2]
	det.ref.sources <- details.layout[3,2]
	det.ref.features <- details.layout[4,2]
	
	imgsubgroupA <- ggroup(cont=vexpgroup)
	imgsubgroupB <- ggroup(cont=vexpgroup)
	
	imgwindow1 <- ggraphics(container=imgsubgroupA)
	addHandlerChanged(imgwindow1, ImgHandler)
	
	imgwindow2 <- ggraphics(container=imgsubgroupA)
	addHandlerChanged(imgwindow2, ImgHandler)

	imgwindow3 <- ggraphics(container=imgsubgroupB)
	addHandlerChanged(imgwindow3, ImgHandler)

	imgwindow4 <- ggraphics(container=imgsubgroupB)
	addHandlerChanged(imgwindow4, ImgHandler)
	
	return()
	
}

